### ISSUE TITLE
Error: The MessagePort for Worker thread 0 is null

### ISSUE THREAD

**Issue by mannershark** [faranalytics/socketnaut#2]
Hi,
I'm really interested in running Socketnaut with Express, but I haven't been able to get it to work.

I first tried this directly on our codebase, which resulted in that error.  
I then created a minimal example based on the sample provided, but I still get the same error: `The MessagePort for Worker thread 0 is null`.

It seems most likely there are some packages that are invalid, but I don't have any specifics to be able to debug that with based on the error message.

Context:
Running in WSL2
node --version v20.17.0

server/server.ts
```
import * as http from 'node:http';
import * as express from 'express';
import { createServiceAgent } from 'socketnaut';

const app = express();

app.get('/', (req, res) => {
  for (let now = Date.now(), then = now + 100; now < then; now = Date.now()); // Block for 100 milliseconds.
  res.send('Hello World!');
});

const server = http.createServer(app); // Configure this HTTP Server however you choose.

server.listen({ port: 1122, host: '127.0.0.1' });
// Specifying port 0 here will instruct the Server to listen on a random port.  
// The Socketnaut Agent will communicate the randomly selected port to the ServiceProxy.

const agent = createServiceAgent({ server });
```

package.json:
```
{
  "name": "socketnaut-test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "node -r ts-node/register/transpile-only --max-old-space-size=${NODE_MAX_OLD_SPACE_SIZE:-4096} server/server.ts"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "express": "4.18.2",
    "socketnaut": "^1.5.3",
    "ts-node": "10.9.1",
    "typescript": "5.5.4"
  }
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "paths": {
      "*": ["types/*"]
    },
    "target": "ES2022",
    "module": "CommonJS",
    "moduleResolution": "node",
    "sourceMap": true,
    "allowJs": true,
    "outDir": "dist",
    "resolveJsonModule": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "downlevelIteration": true,
    "lib": ["DOM", "ES2022"],
    "removeComments": false,
    "baseUrl": "./",
    "typeRoots": ["./node_modules/@types", "types/*"],
    "skipLibCheck": true,
    "useDefineForClassFields": false
  },
  "exclude": ["node_modules", "dist"],
  "include": ["./**/*.ts"],
}
```

**Comment by adamjpatterson** [comment]
@mannershark Thank you for submitting this issue and thank you for using Socketnaut.

The `Error` indicates that `server/server.ts` is being ran as the main thread, as it reports a thread ID of `0`.  This is also evidenced by the `start` script, which runs `server/server.ts` i.e., "start": "node ... server/server.ts".

Socketnaut will scale your `server/server.ts` according to arguments passed to the `createServiceProxy` helper function in the `index.ts` module.  You specify the path to your module as an argument to the `workerURL` parameter of the `createServiceProxy` helper function.  **You run your application by starting the `index.ts` module.**   You can see an example where the scaled module is specified here:  https://github.com/faranalytics/socketnaut/blob/main/examples/socketnaut_express/index.js#L12

I made an improvement to the documentation of the [Express example](https://github.com/faranalytics/socketnaut/tree/main/examples/socketnaut_express) in order to make it more clear that `index.js` is to be ran as the main thread.

Please let me know this explanation isn't sufficient.  Thank you again for submitting this issue.

**Comment by mannershark** [comment]
Thanks! I indeed missed the index.js file. I've managed to get the sample from the documentation running now.
